### ISSUE TITLE
Adding headers: Unable to access the response before visiting a page

### ISSUE THREAD

**Issue by araines** [Behatch/contexts#104]
Attempting to run this scenario:

```
Feature: Creating new sports
  Scenario: Successful creation
    Given I add "Accept" header equal to "application/json"
```

With no other steps, I get this exception:

```
Feature: Creating new sports

  Scenario: Successful creation                                  # features/functional/sports/store.feature:3
    Given I add "Accept" header equal to "application/json"      # Sanpi\Behatch\Context\RestContext::iAddHeaderEqualTo()



  [Behat\Mink\Exception\DriverException]
  Unable to access the response before visiting a page

```

So for some reason I'm getting an exception when trying to set up headers prior to sending the request - it seems like its trying to access the response for some reason.  I've been scratching my head over this for a while, can't see what I'm doing wrong.

**Comment by jdecool** [comment]
Is a release planned ?

Because this fix isn't tag actually ...

**Comment by sanpii** [comment]
@jdecool sorry I hadn’t published the release. Is fixed.

**Comment by jdecool** [comment]
Yeah ! You're very fast ;)

Thanks a lot.
