### ISSUE TITLE
Make Contexts extandable

### ISSUE THREAD

**Issue by theofidry** [Behatch/contexts#124]
Could it be possible to pass private properties and methods from private to protected so that we can inherit of those contexts?

**Comment by sanpii** [comment]
I don’t like this idea. More protected functions is more api to maintian stable.

I do not see in which cases contexts inheritage is helpful. This means may be a lack of decoupling?

**Comment by theofidry** [comment]
I find the `getJson` usefull so having it protected would be convenient although not necessary. Aside from that maybe getters would be enough.

In my case I would like to extend `JsonContext` to test if my response is a `JSON-LD` response instead of a JSON (which is equivalent to testing if the response is a JSON one with a specific content-type header `application/ld+json`.

**Comment by sanpii** [comment]
Ok. I this case, if ``JsonContext::theResponseShouldBeInJson()`` return the ``Json`` object, could be a solution?

**Comment by theofidry** [comment]
Erf my mistake. Indeed in this case the `JsonContext::theResponseShouldBeInJson()` works fine! :)

**Comment by theofidry** [comment]
I run into the problem again: for instance I which to extend the RestContext to add a method to check the type of response and the Content-Type.

**Comment by sanpii** [comment]
> the type of response

What is it?

> the Content-Type.

Use `RestContext::theHeaderShouldBeEqualTo()`.

**Comment by theofidry** [comment]
OK thanks.

**Comment by akomm** [comment]
Actually, `JsonContext::theResponseShouldBeInJson()` does not return the json.
