### ISSUE TITLE
Removed tags?

### ISSUE THREAD

**Issue by dunglas** [Behatch/contexts#126]
It seems that some tags have been silently removed (2.3 and recently 2.2). It breaks our projects requiring Behatch (errors like `The requested package behatch/contexts could not be found in any version, there may be a typo in the package name.` while running `composer update`), it breaks semver and it is against best practices.

**Comment by COil** [comment]
:+1:

**Comment by theofidry** [comment]
Same problem here.

**Comment by nass600** [comment]
Same here

**Comment by dunglas** [comment]
@sanpii, is it possible to tag a new version?

**Comment by dinamic** [comment]
Same here. Unable to add custom header to POST requests. Even the example fails.

```
    Scenario: Add header
        Given I add "xxx" header equal to "yyy"
        When I send a GET request to "/rest/index.php"
        Then I should see "HTTP_XXX : yyy"
```

```
  Scenario: Add header
    Given I add "xxx" header equal to "yyy"

  [Behat\Mink\Exception\DriverException]
  Unable to access the response before visiting a page
```
