### ISSUE TITLE
Invalid detection of false value in JSON

### ISSUE THREAD

**Issue by klinkiap** [Behatch/contexts#132]
There is a bug in detection of false value. 

I have a step: `And the JSON node "is_completed" should be equal to "false"`
and I'm getting this error: `The node value is 'false' (Exception)`

I tried  `And the JSON node "is_completed" should contain "false" ` as well but it is not working either. 

True value works fine.

**Comment by anjalirana** [comment]
I am facing same problem - any update?

**Comment by wadjei** [comment]
I ran into this and in the end worked around it by adding a shim to my feature context to translate the string true/false into proper booleans. 
It's a bit messy but got the job done...

```
# FeatureContext.php
...
use Sanpi\Behatch\Context\JsonContext;
use Behat\Behat\Hook\Scope\BeforeScenarioScope;

...


    /**
     *  @BeforeScenario
     */
    public function getBehatchJsonContext(BeforeScenarioScope $scope)
    {
        $environment = $scope->getEnvironment();

        $this->behatchJsonContext = $environment->getContext('Sanpi\Behatch\Context\JsonContext');
    }

    /**
     * @Then the JSON node :node should be boolean :boolAsString
     */
    public function theJsonNodeShouldBeBooleanFalse($node, $boolAsString)
    {
        if (!$this->behatchJsonContext) {
            $this->assert->markTestSkipped('Behatch JsonContext cannot be used.');
        }

        if ($boolAsString == 'false') {
            $bool = false;
        } elseif ($boolAsString == 'true') {
            $bool = true;
        } else {
            $this->assert->markTestSkipped(
                'Invalid value '.var_export($boolAsString,true).' supplied for boolean comparison.'
            );
        }

        // call the behatch JsonContext with a valid boolean.
        return $this->behatchJsonContext->theJsonNodeShouldBeEqualTo($node, $bool);
    }
```

And in the scenario, changing 
```
And the JSON node "is_completed" should be equal to "false"
```
to
```
And the JSON node "is_completed" should be boolean "false"
```

**Comment by wadjei** [comment]
There's actually a pair of open pull requests - https://github.com/Behatch/contexts/pull/115 and https://github.com/Behatch/contexts/pull/116 - which would address this

**Comment by MLKiiwy** [comment]
#116 is better I think

**Comment by sanpii** [comment]
#116 merged.

**Comment by MLKiiwy** [comment]
Great and could you create a new release version please ?

**Comment by sanpii** [comment]
@MLKiiwy travis is red, I try to fix that before release :smiley:
