### ISSUE TITLE
Tag 2.3

### ISSUE THREAD

**Issue by tophsic** [Behatch/contexts#152]
Did I miss something or tag 2.3 was removed ? I miss it :cry:

**Comment by sanpii** [comment]
Push again.

**Comment by tophsic** [comment]
:+1: Sorry for my reactivity :wink:

**Comment by tophsic** [comment]
Some of what I proposed for `SystemContext` are missing. Do I need to PR again?

**Comment by sanpii** [comment]
> Do I need to PR again?
No, the commits are on master but after the 2.3 tag. I have pushed the old tag, not created a new on HEAD.

**Comment by tophsic** [comment]
Ok. Maybe I missed something but if I look at Github event history, you created tag 2.3 on nov 20th and published it on nov 27th and I think I had time to checkout it and see these commits. But don't worry, I will waiting 2.4 release and base my dependencies on master or my fork waiting for it.
