### ISSUE TITLE
RestContext does not reset headers between scenarios

### ISSUE THREAD

**Issue by samusenkoiv** [Behatch/contexts#165]
I am testing my api with Authorization header, and when I set a header in one scenario it is still exist in the next scenario. 
Do I do something wrong or it is desired behaviour  ?

**Comment by sanpii** [comment]
This is a bug, see #164

**Comment by samusenkoiv** [comment]
It will take a while before https://github.com/FriendsOfPHP/Goutte/pull/261#partial-pull-merging is merged. Can I somehow use vincentchalamon fix already ?

**Comment by razbakov** [comment]
Goutte is merged. Update here?

**Comment by sanpii** [comment]
#164 merged.
