### ISSUE TITLE
How can I get access to array element ? 

### ISSUE THREAD

**Issue by samusenkoiv** [Behatch/contexts#169]
Provided I have this body in response:

> {
>   "myobj" : [
>     { "key": "value" },
>     { "key": "value" },
>     { "key": "value" }
>   ]
> }

How can I check some value in this array  ? I was trying to do this:

> And the JSON node "myobj.1.key" should be equal to the string "value"

But I get this message then:

>  Failed to evaluate expression 'myobj.1.key' (Exception)

Do I do something wrong or this feature wasn't implemented yet  ?

**Comment by sanpii** [comment]
> How can I check some value in this array ?

Simply:

```
myobj[1].key
```

Features can be a good documentation: https://github.com/Behatch/contexts/blob/master/tests/features/json.feature#L25

**Comment by samusenkoiv** [comment]
> Features can be a good documentation: https://github.com/Behatch/contexts/blob/master/tests/features/json.feature#L25
Yes, you're right. Thank you @sanpii .
