### ISSUE TITLE
justinrainbow/json-schema required version

### ISSUE THREAD

**Issue by diyankk** [Behatch/contexts#181]
Hello,

I am using behatch/contexts v2.5 and need to use justinrainbow/json-schema package in a project. I see that the required version for that one is ~1.4. Would it be possible to change this requirement to v2.0 or later of justinrainbow/json-schema? 

Here is the output of composer install command with the issue:

composer require justinrainbow/json-schema
Using version ^2.0 for justinrainbow/json-schema
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - behatch/contexts 2.5 requires justinrainbow/json-schema ~1.4 -> satisfiable by justinrainbow/json-schema[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.6.1, v1.6.0] but these conflict with your requirements or minimum-stability.
    - behatch/contexts 2.5 requires justinrainbow/json-schema ~1.4 -> satisfiable by justinrainbow/json-schema[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.6.1, v1.6.0] but these conflict with your requirements or minimum-stability.
    - behatch/contexts 2.5 requires justinrainbow/json-schema ~1.4 -> satisfiable by justinrainbow/json-schema[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.6.1, v1.6.0] but these conflict with your requirements or minimum-stability.
    - Installation request for behatch/contexts (locked at 2.5, required as ^2.4) -> satisfiable by behatch/contexts[2.5].

Installation failed, reverting ./composer.json to its original content.

Thank you,

Diyan

**Comment by sanpii** [comment]
I am also blocked by `kherge/box` that required `~1.3`.

**Comment by sanpii** [comment]
https://github.com/box-project/box2/issues/149

**Comment by Nicofuma** [comment]
Hello, I am running in the same issue.
But there is an issue due to herrera-io/json (required by kherge/box) which is abandoned...

**Comment by Nicofuma** [comment]
In the mean time I have forked the library to support justinrainbow/json-schema: ^2.0 (they have released the 3.0 today but there is, again, a BC break around the RefResolver)
https://github.com/Nicofuma/behatch-contexts

**Comment by sanpii** [comment]
Done via #191
