### ISSUE TITLE
oneOf with $ref seems not be working

### ISSUE THREAD

**Issue by philippecarle** [Behatch/contexts#185]
Hi,

I've played with GeoJson schema validation and can't figure out why I keep getting `Failed to match exactly one schema error`.

I guess it may be due to a wrong handling of `"oneOf"` in combination of `"$ref"` ?

Here is my schema : 

```json

{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Geo JSON object",
  "description": "Schema for a Geo JSON object",
  "type": "object",
  "required": [ "type" ],
  "oneOf": [
    { "$ref": "#/definitions/feature" },
    { "$ref": "#/definitions/featureCollection" }
  ],
  "definitions": {
    "feature": {
      "title": "Feature",
      "description": "A Geo JSON feature object",
      "required": [ "geometry", "properties" ],
      "properties": {
        "type": { "enum": [ "Feature" ] },
        "geometry": {
          "type": [ "array","null" ]
        },
        "properties": {
          "type": [ "object", "null" ]
        }
      }
    },
    "featureCollection": {
      "title": "FeatureCollection",
      "description": "A Geo JSON feature collection",
      "required": [ "features" ],
      "properties": {
        "type": { "enum": [ "FeatureCollection" ] },
        "features": {
          "type": "array",
          "items": { "$ref": "#/definitions/feature" }
        }
      }
    }
  }
}

```

It's working when I try to do this against a GeoJson feature : 

```json

{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Geo JSON object",
  "description": "Schema for a Geo JSON object",
  "type": "object",
  "required": [ "type" ],
  "oneOf": [
    {
      "title": "Feature",
      "description": "A Geo JSON feature object",
      "required": [ "geometry", "properties" ],
      "properties": {
        "type": { "enum": [ "Feature" ] },
        "geometry": {
          "type": [ "array","null" ]
        },
        "properties": {
          "type": [ "object", "null" ]
        }
      }
    }
  ]
}

```

**Comment by sanpii** [comment]
Hi,

Have you try to valide your json with the `validate-json` command line tool? Json context is just a bridge to [https://github.com/justinrainbow/json-schema](justinrainbow/json-schema).

**Comment by philippecarle** [comment]
Ok I've been working once again on this and it validates with the justinrainbow's package.

Here are the files used for my tests : 
[example.zip](https://github.com/Behatch/contexts/files/518431/example.zip)

I really can't figure out what I'm doing wrong :(

**Comment by philippecarle** [comment]
Ok i got it working by pointing on the dev-master of this repo… now i'm getting a "The maximum stack depth has been exceeded" error from justinrainbow/json-schema which has been fixed since more than one year. I should really consider coding these tests with a very verbose set of PHPunit tests, as this package, regarding to its very outdated dependencies and to the lack of patched versions, can't meet production requirements… :(
(i'm not whining here, just saying the purpose of this can't fit to "real-life" testing)

**Comment by sanpii** [comment]
Ok, it’s related to #181
