### ISSUE TITLE
v2.6 broke our test suite

### ISSUE THREAD

**Issue by teohhanhui** [Behatch/contexts#200]
https://travis-ci.org/api-platform/core/jobs/207362131

**Comment by sanpii** [comment]
Fixed & released. Sorry for the inconvenience.

**Comment by soyuka** [comment]
Is it released? Can't find the 2.6.1 tag [here](https://github.com/Behatch/contexts/tags)

**Comment by sanpii** [comment]
@soyuka pushed, thank you.
