### ISSUE TITLE
Dependency on a non-existent service "mink".

### ISSUE THREAD

**Issue by coulon-xyz** [Behatch/contexts#203]
Hi,

I would like to use Behatch to test my APIs, but I can't figure out how to run it.
I've got the following message:

 [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                   
 The service "behatch.http_call.listener" has a dependency on a non-existent service "mink"

my yml is:
# behat.yml
default:
    extensions:
      Behatch\Extension: ~
    suites:
        core:
            paths:
                - %paths.base%/features
        default:
            contexts:
                - behatch:context:browser
                - behatch:context:debug
                - behatch:context:system
                - behatch:context:json
                - behatch:context:table
                - behatch:context:rest
                - behatch:context:xml

and my composer.json 
{
  "require-dev": {
    "behat/behat": "^3.3",
    "phpunit/phpunit": "^5.7",
    "behatch/contexts": "^2.6",
    "behat/mink": "^1.7"
  }
}

Sounds like there is something fairly obvious that i'm missing.

**Comment by sanpii** [comment]
Hello,

You should enable the mink extension: https://github.com/Behatch/skeleton/blob/master/behat.yml.dist#L16

**Comment by coulon-xyz** [comment]
Thanks a lot. It works now.
