### ISSUE TITLE
failing xliff schema validation for locale es

### ISSUE THREAD

**Issue by jordicaballero** [Behatch/contexts#213]
Hello

I avoid this issue running behat forcing english locale:
`vendor/bin/behat --lang=en`

When I run behat in my env with spanish locale, it produces an InvalidResourceException with messages:
`Invalid resource provided: "1.2"; Errors: [ERROR 1845] Element 'xliff': No matching global declaration available for the validation root. (in /var/www/myproject/ - line 1, column 0)`

Fixed adding property:
xmlns="urn:oasis:names:tc:xliff:document:1.2"
 into xliff root at /vendor/behatch/contexts/i18n/es.xliff
`
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file ... etc etc
`
Thanks

**Comment by sanpii** [comment]
Fixed in master and [2.7.1](https://github.com/Behatch/contexts/releases/tag/2.7.1). Thank you!
