### ISSUE TITLE
Class Aliases in package HttpCall

### ISSUE THREAD

**Issue by outermedia-cbo** [Behatch/contexts#225]
Hi @sanpii,

It looks like all `class_alias` in `src/class_aliases/HttpCall/` miss `HttpCall` in the path.

E.g. src/class_aliases/HttpCall/Request.php:

Line 5: `class_alias('\\Behatch\\Request', '\\Sanpi\\Behatch\\Request');`

I would expect
`class_alias('\\Behatch\\HttpCall\\Request', '\\Sanpi\\Behatch\\HttpCall\\Request');`

I am asking because I get the following error:

>   [ReflectionException]                                
  Class Sanpi\Behatch\HttpCall\Request does not exist  
>                                                                                                                  
>  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Warning: Class '\Behatch\Request' not found                

Regards,
Christoph

**Comment by sanpii** [comment]
Fixed, thank you.
