### ISSUE TITLE
Question about guzzlehttp/guzzle dependency

### ISSUE THREAD

**Issue by fbourigault** [Behatch/contexts#231]
`guzzlehttp/guzzle` was added as dependency while adding support for PHP 7.2.

Why it was not added as dev dependency?

https://github.com/Behatch/contexts/blob/5750314dba1d9901a8cff56c50241739e228886d/composer.json#L12

**Comment by sanpii** [comment]
It’s an error, guzzle is required for development dependency only.

**Comment by fbourigault** [comment]
Is it possible to get a release including this fix?

**Comment by sanpii** [comment]
@fbourigault done.

**Comment by fbourigault** [comment]
Awesome! Thank you.
