### ISSUE TITLE
Packagist not updating

### ISSUE THREAD

**Issue by elkangaroo** [Behatch/contexts#238]
Hi, do you know why packagist.org is not updating your package (see https://packagist.org/packages/behatch/contexts#dev-master)?
Latest revision there is 32dcd9bbdac6e261b675251f77c2619305e1c51c from December, everything after that cannot be checked out via composer, because packagist does not know it :(.

**Comment by sanpii** [comment]
Yes, I received a mail because the composer.json is invalide.

**Comment by sanpii** [comment]
Mail sent to packagist, beerware is now a SPDX license: https://spdx.org/licenses/Beerware.html

The composer.json is valid:
```
$ cps validate
./composer.json is valid
$ cps --version
Composer version 1.6.3 2018-01-31 16:28:17
```

**Comment by elkangaroo** [comment]
Thx! It's working again, Packagist now has the latest master version! Closing the issue.
