### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hippy-azimov** [Behatch/contexts#253]
Hi there, this library is cool, but I couldn't found any documentations.

**Comment by sanpii** [comment]
Hello,

All informations is in [README](https://github.com/Behatch/contexts/blob/master/README.md) and you can find examples in [features](https://github.com/Behatch/contexts/tree/master/tests/features) directory.

Do you need more information?

**Comment by hippy-azimov** [comment]
Wow, good, thanks for examples!

**Comment by sanpii** [comment]
I just added a note about that: https://github.com/Behatch/contexts#examples
