### ISSUE TITLE
Support Symfony 5 packages

### ISSUE THREAD

**Issue by pana1990** [Behatch/contexts#279]
Hi community, I can't update my project to Symfony 5.0 because this is unsupported by behatch/contexts (property-access, http-foundation and dom-crawler component). Any information about plan for this support ?

i can try to send pull request.

**Comment by pura** [comment]
Hi @pana1990 and everyone
Any progress on this? I don't wanna repeat the work if anyone has already started.

**Comment by derekalmond** [comment]
would also like to see this working.

**Comment by pana1990** [comment]
Hi community, i was waiting for any reply from team leader...to start pr.
@sanpii
