### ISSUE TITLE
Unable to access the response before visiting a page

### ISSUE THREAD

**Issue by fesor** [Behatch/contexts#89]
https://github.com/sanpii/behatch-contexts/blob/master/src/HttpCall/HttpCallListener.php#L57

mink throws DriverException which not inherited from LogicException, so tests failing.

I'am using Mink with BrowserKit.

**Comment by dinamic** [comment]
The link to the 2.2 tagged release does not work. Also listing the available tags for the repo is not showing 2.2.

Can you please have a look and tag the release again? Thanks.
