### ISSUE TITLE
$ref not working

### ISSUE THREAD

**Issue by ecentinela** [Behatch/contexts#95]
This is my documents.json file content:

```
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "type": "array",
    "required": true,
    "items": {
        "$ref": "document.json",
        "required": true
    }
}
```

And this is my document.json file content:

```
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "type": "object",
    "required": true,
    "additionalProperties": false,
    "properties": {
        "id": {
            "type": "string",
            "required": true
        },
        "inexistent_property": {
            "type": "string",
            "required": true
        }
    }
}
```

When I pass this json response:

```
[
{
    "id": "an_id"
}
]
```

It passes the tests.

I'm doing something wrong?

**Comment by araines** [comment]
I'm still having problems with $ref resolution (on commit 85537f70350c6e4e1a95f235082b5d49fd8b2c0e)

Will try to confirm the issue ASAP and give a workable example.

**Comment by araines** [comment]
It was a bug with the external JSON Schema library.  I can confirm that $ref is otherwise working!

**Comment by sanpii** [comment]
This is normally fixed in `master`. Can you confirm?
